//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseManagemnet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblBatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBatch()
        {
            this.tblStudent_info = new HashSet<tblStudent_info>();
        }
    
        public int ID { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
       
        public System.DateTime Start_time { get; set; }
        [Required]
        public string Duraion { get; set; }
        [Required]
        public int CourseId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudent_info> tblStudent_info { get; set; }
        public virtual tblCourse tblCourse { get; set; }
    }
}
