//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseManagemnet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblStudent_info
    {
        public int ID { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [StringLength(20, MinimumLength = 5)]
        public string Name { get; set; }
        [Required]
        [DataType(DataType.PhoneNumber)]
        public int Cell { get; set; }

        [Required]
      
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [StringLength(20, MinimumLength = 5)]
        public string Father_name { get; set; }


        [Required]
        [DataType(DataType.Text)]
        [StringLength(20, MinimumLength =5)]
        public string Mother_name { get; set; }


        [Required]
        [DataType(DataType.MultilineText)]
        public string Adress { get; set; }


        [Required]
        public int Course_id { get; set; }


        [Required]
        public int Batch_id { get; set; }
     
        public string Result { get; set; }
    
        public virtual tblBatch tblBatch { get; set; }
        public virtual tblCourse tblCourse { get; set; }
    }
}
